import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import SearchBar from "@/components/SearchBar";

const figtree = Figtree({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={figtree.className}>
        <SearchBar />
        <main>{children}</main>
      </body>
    </html>
  );
}
